// =============================================
//  api.js — Congress.gov + Anthropic API calls
// =============================================

// ---- Static Data Loading ----

async function fetchRepsIndex() {
  try {
    const res = await fetch('data/reps-index.json');
    if (!res.ok) return {};
    return await res.json();
  } catch (e) { return {}; }
}

async function fetchStandaloneQuotes() {
  try {
    const res = await fetch('data/quotes.json');
    if (!res.ok) return [];
    const data = await res.json();
    return data.quotes || [];
  } catch (e) { return []; }
}

async function fetchRecentBills() {
  // Reads from static data/cache.json generated by the batch processor.
  try {
    const res = await fetch('data/cache.json');
    if (!res.ok) throw new Error('Static data file not found');
    const data = await res.json();
    if (!data.bills || data.bills.length === 0) {
      return getDemoBills();
    }
    return data.bills;
  } catch (e) {
    console.warn('Failed to load static cache.json, falling back to graceful degradation UI (demo bills)', e);
    return getDemoBills();
  }
}

function detectStage(bill, actions) {
  // Walk actions newest-first to find current stage
  const sorted = [...actions].sort((a,b) => new Date(b.actionDate) - new Date(a.actionDate));
  for (const action of sorted) {
    const text = (action.text || '').toLowerCase();
    const type = (action.type || '').toLowerCase();
    if (text.includes('vetoed by president') || text.includes('pocket veto') ||
        (text.includes('returned to') && text.includes('with objections')))
      return { key: 'vetoed', label: 'Vetoed' };
    if (text.includes('signed by president') || text.includes('became public law'))
      return { key: 'signed', label: 'Signed into law' };
    if (text.includes('passed senate') || text.includes('senate passed'))
      return { key: 'senate', label: 'Senate passed' };
    if (text.includes('passed house') || text.includes('house passed'))
      return { key: 'house', label: 'House passed' };
    if (text.includes('senate') && (text.includes('committee') || text.includes('referred')))
      return { key: 'committee', label: 'Senate committee' };
    if (text.includes('house') && (text.includes('committee') || text.includes('referred')))
      return { key: 'committee', label: 'House committee' };
    if (text.includes('conference'))
      return { key: 'conference', label: 'Conference' };
  }
  return { key: 'introduced', label: 'Introduced' };
}

function buildPipeline(bill, actions) {
  const steps = ['Introduced', 'Committee', 'House floor', 'Senate floor', 'Conference', 'Signed'];
  const stageOrder = { introduced: 0, committee: 1, house: 2, senate: 3, conference: 4, signed: 5, vetoed: 5 };
  const stage = detectStage(bill, actions);
  const currentIndex = stageOrder[stage.key] ?? 0;
  return { steps, currentIndex };
}

function estimateLikelihood(stageKey, bill, actions) {
  // Simple heuristic — in production you'd use vote counts, co-sponsor counts, etc.
  const base = { introduced: 12, committee: 28, house: 52, senate: 68, conference: 82, signed: 100, vetoed: 0 };
  let pct = base[stageKey] || 10;
  // More co-sponsors = slightly higher likelihood
  const cosponsors = bill.cosponsors?.count || 0;
  if (cosponsors > 50) pct = Math.min(pct + 10, 95);
  else if (cosponsors > 20) pct = Math.min(pct + 5, 95);
  return pct;
}

function formatSponsor(sponsor) {
  if (!sponsor) return 'Unknown sponsor';
  const party = sponsor.party ? `(${sponsor.party})` : '';
  const state = sponsor.state || '';
  return `${sponsor.fullName || sponsor.name || 'Unknown'} ${party} ${state}`.trim();
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  const s = String(dateStr).trim();
  // ISO YYYY-MM-DD: format parts directly (no UTC/local day shift); output mm-dd-yy.
  const iso = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return `${iso[2]}-${iso[3]}-${iso[1].slice(-2)}`;
  try {
    const d = new Date(s);
    if (isNaN(d)) return s;
    const dd = String(d.getDate()).padStart(2,'0');
    const mm = String(d.getMonth()+1).padStart(2,'0');
    const yy = String(d.getFullYear()).slice(-2);
    return `${mm}-${dd}-${yy}`;
  } catch(e) { return s; }
}

function cleanHtml(html) {
  const tmp = document.createElement('div');
  tmp.innerHTML = html;
  return tmp.textContent || tmp.innerText || '';
}

// ---- Anthropic AI Analysis ----

// ---- Demo bills (shown when no API key is configured) ----

function getDemoBills() {
  return [
    {
      id: 'demo-1',
      title: 'American Infrastructure Renewal Act of 2025',
      code: 'S.1042',
      stage: 'senate',
      stageLabel: 'Senate floor',
      date: 'Apr 14, 2025',
      sponsor: 'Sen. Klobuchar (D-MN)',
      pipeline: ['Introduced','Committee','House passed','Senate floor','Conference','Signed'],
      currentStep: 3,
      likelihood: 62,
      likelihoodLabel: 'Possible',
      likelihoodReason: 'Bipartisan support for core provisions, but Republican opposition to wage requirements and EV mandates creates real friction. Conference committee likely.',
      summaryText: '',
      analyzed: true,
      sections: [
        { label: 'Transportation', items: [
          { main: 'Allocates $120B for highway and bridge repair over 5 years.', detail: 'Funds distributed via formula grants to states weighted by lane-miles and vehicle miles traveled. States must match 20% of funds. Projects over $100M require environmental review under NEPA.', comments: [{ party:'d', text:"Sen. Klobuchar (D-MN): 'This is the largest bridge investment since the Highway Act.'" },{ party:'r', text:"Sen. Capito (R-WV): 'Supportive, but wants prevailing wage provisions removed.'" }] },
          { main: 'Establishes $12B EV charging corridor program across interstates.', detail: 'Targets 500K new public charging ports by 2030. 50% must be fast-chargers. Priority corridors include rural and underserved areas.', comments: [{ party:'r', text:"Sen. Barrasso (R-WY): 'Opposed — market should drive EV adoption, not mandates.'" }] }
        ]},
        { label: 'Broadband', items: [
          { main: 'Provides $65B to expand high-speed internet access to unserved rural areas.', detail: 'Commerce Dept. administers grants to ISPs and co-ops. Minimum speed: 100/20 Mbps. ISPs must offer low-income tier at $30/mo or less to qualify.', comments: [{ party:'d', text:"Rep. Matsui (D-CA): 'Closes the digital divide. Strongly in favor.'" },{ party:'n', text:"CBO estimates 98% rural coverage by 2028 if funds are fully deployed." }] }
        ]}
      ],
      criticisms: [
        { who: 'Sen. Capito (R-WV) & GOP caucus', why: 'Prevailing wage requirements are seen as inflating project costs by 15–20%, favoring union labor over open competition.' },
        { who: 'Fiscal hawks (both parties)', why: 'No pay-for mechanism included — the bill adds directly to the deficit.' }
      ],
      gaps: [
        'Rail and public transit funding is absent — no allocation for Amtrak expansion or urban transit.',
        'Climate resilience standards not addressed — no requirement that rebuilt infrastructure meet updated flood or heat thresholds.',
        'No provision for maintenance funding after construction.'
      ]
    },
    {
      id: 'demo-2',
      title: "Protecting Medicare's Drug Pricing Negotiation Act",
      code: 'H.R.3211',
      stage: 'committee',
      stageLabel: 'Senate Finance Cmte.',
      date: 'Apr 9, 2025',
      sponsor: 'Rep. Pallone (D-NJ)',
      pipeline: ['Introduced','House Cmte.','House passed','Senate Finance','Senate floor','Signed'],
      currentStep: 3,
      likelihood: 38,
      likelihoodLabel: 'Unlikely',
      likelihoodReason: 'Strong Democratic support but near-unanimous Republican opposition and intense pharmaceutical lobbying make passage unlikely without significant compromise.',
      summaryText: '',
      analyzed: true,
      sections: [
        { label: 'Prescription drug pricing', items: [
          { main: 'Expands Medicare authority to negotiate prices for 50 additional drugs per year (up from 20).', detail: 'HHS must publish negotiated maximum fair prices 60 days before they take effect. Manufacturers who refuse face an excise tax scaling to 95% of U.S. sales.', comments: [{ party:'d', text:"Rep. Pallone (D-NJ): 'Pharma has gotten away with price gouging for decades.'" },{ party:'r', text:"Sen. Thune (R-SD): 'Concerned this will reduce R&D investment for rare diseases.'" },{ party:'n', text:"AARP projects average senior savings of $800/year if enacted." }] },
          { main: 'Caps annual out-of-pocket Medicare Part D costs at $2,000 starting 2026.', detail: 'Replaces current catastrophic coverage threshold. Manufacturers must pay rebates if prices rise faster than inflation.', comments: [{ party:'d', text:"Sen. Sanders (I-VT): 'Good start — we need full Medicare for All.'" }] }
        ]}
      ],
      criticisms: [
        { who: 'PhRMA & pharmaceutical industry', why: 'Price controls will reduce R&D revenue, potentially killing pipeline drugs for rare diseases and cancers.' },
        { who: 'CBO (nonpartisan concern)', why: 'Projects the bill could reduce new drugs entering the market by 13 over the next decade.' }
      ],
      gaps: [
        'Insulin pricing not specifically addressed — non-Medicare patients under 65 are excluded.',
        'No provisions for dental, vision, or hearing coverage under Medicare.',
        'Pharmacy benefit manager (PBM) practices are not addressed.'
      ]
    },
    {
      id: 'demo-3',
      title: 'National Defense Authorization Act FY2026',
      code: 'S.880',
      stage: 'house',
      stageLabel: 'House Armed Services',
      date: 'Mar 28, 2025',
      sponsor: 'Sen. Wicker (R-MS)',
      pipeline: ['Introduced','Senate Armed Svcs.','Senate passed','House Armed Svcs.','House floor','Conference','Signed'],
      currentStep: 3,
      likelihood: 85,
      likelihoodLabel: 'Likely',
      likelihoodReason: 'The NDAA passes every year with broad bipartisan support. Specific provisions may be amended in conference but the bill is near-certain to be signed.',
      summaryText: '',
      analyzed: true,
      sections: [
        { label: 'Defense spending', items: [
          { main: 'Authorizes $923B in total defense spending for FY2026, a 3.5% increase.', detail: 'Base budget of $874B plus $49B in overseas contingency operations. Largest line items: personnel ($180B), O&M ($310B), procurement ($160B).', comments: [{ party:'r', text:"Sen. Wicker (R-MS): 'Essential to maintain our edge over China and Russia.'" },{ party:'d', text:"Sen. Warren (D-MA): 'We should audit the Pentagon before writing blank checks.'" }] }
        ]},
        { label: 'Personnel', items: [
          { main: 'Authorizes a 4.5% pay raise for all active-duty military personnel.', detail: 'Applies to all E-1 through O-10 pay grades effective Jan 1, 2026. Matching raise for reserve components during active duty periods.', comments: [{ party:'d', text:"Rep. Gallego (D-AZ): 'Bipartisan support — our troops deserve this.'" }] }
        ]}
      ],
      criticisms: [
        { who: 'Sen. Warren (D-MA) & progressive Democrats', why: 'Oppose the spending level without a mandatory Pentagon audit — DoD has failed its audit for six consecutive years.' },
        { who: 'Arms control advocates', why: 'Hypersonic missile expansion is seen as destabilizing with no diplomatic counterbalance in the bill.' }
      ],
      gaps: [
        'Cybersecurity workforce shortfall — Pentagon projects a deficit of 40,000 cyber personnel by 2027 with no training pipeline addressed.',
        'Military housing quality improvements absent despite documented unsafe conditions on bases.',
        'Climate readiness not addressed — no funding for hardening bases against flooding or wildfire.'
      ]
    }
  ];
}
